name: Build and test
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8.0.362+9'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn install -DskipTests -Dgpg.skip
      - name: Test with Maven
        run: mvn test
